/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      // Design System Token Integration
      gap: {
        'ds-xs': 'var(--ds-gap-xs)',
        'ds-sm': 'var(--ds-gap-sm)',
        'ds-md': 'var(--ds-gap-md)',
        'ds-lg': 'var(--ds-gap-lg)',
        'ds-xl': 'var(--ds-gap-xl)',
      },
      spacing: {
        'ds-none': 'var(--ds-spacing-none)',
        'ds-3xs': 'var(--ds-spacing-3xs)',
        'ds-2xs': 'var(--ds-spacing-2xs)',
        'ds-xs': 'var(--ds-spacing-xs)',
        'ds-sm': 'var(--ds-spacing-sm)',
        'ds-md': 'var(--ds-spacing-md)',
        'ds-lg': 'var(--ds-spacing-lg)',
        'ds-xl': 'var(--ds-spacing-xl)',
        'ds-2xl': 'var(--ds-spacing-2xl)',
        'ds-3xl': 'var(--ds-spacing-3xl)',
        'ds-4xl': 'var(--ds-spacing-4xl)',
        'ds-5xl': 'var(--ds-spacing-5xl)',
        'ds-6xl': 'var(--ds-spacing-6xl)',
        'ds-7xl': 'var(--ds-spacing-7xl)',
        'ds-8xl': 'var(--ds-spacing-8xl)',
        'ds-9xl': 'var(--ds-spacing-9xl)',
      },
      borderRadius: {
        'ds-none': 'var(--ds-radius-none)',
        'ds-sm': 'var(--ds-radius-sm)',
        'ds-base': 'var(--ds-radius-base)',
        'ds-md': 'var(--ds-radius-md)',
        'ds-lg': 'var(--ds-radius-lg)',
        'ds-xl': 'var(--ds-radius-xl)',
        'ds-2xl': 'var(--ds-radius-2xl)',
        'ds-3xl': 'var(--ds-radius-3xl)',
        'ds-full': 'var(--ds-radius-full)',
        'ds-dialog': 'var(--ds-radius-dialog)',
        'ds-badge': 'var(--ds-radius-badge)',
        'ds-button': 'var(--ds-radius-button)',
        'ds-input': 'var(--ds-radius-input)',
        'ds-card': 'var(--ds-radius-card)',
      },
      maxWidth: {
        'ds-dialog-sm': 'var(--ds-width-dialog-sm)',
        'ds-dialog-md': 'var(--ds-width-dialog-md)',
        'ds-dialog-lg': 'var(--ds-width-dialog-lg)',
        'ds-dialog-xl': 'var(--ds-width-dialog-xl)',
        'ds-dialog-2xl': 'var(--ds-width-dialog-2xl)',
        'ds-dialog-3xl': 'var(--ds-width-dialog-3xl)',
        'ds-dialog-4xl': 'var(--ds-width-dialog-4xl)',
        'ds-dialog-5xl': 'var(--ds-width-dialog-5xl)',
        'ds-dialog-6xl': 'var(--ds-width-dialog-6xl)',
        'ds-dialog-7xl': 'var(--ds-width-dialog-7xl)',
        'ds-dialog-full': 'var(--ds-width-dialog-full)',
      },
      width: {
        'ds-icon-2xs': 'var(--ds-icon-2xs)',
        'ds-icon-xs': 'var(--ds-icon-xs)',
        'ds-icon-sm': 'var(--ds-icon-sm)',
        'ds-icon-md': 'var(--ds-icon-md)',
        'ds-icon-lg': 'var(--ds-icon-lg)',
        'ds-icon-xl': 'var(--ds-icon-xl)',
        'ds-icon-2xl': 'var(--ds-icon-2xl)',
      },
      height: {
        'ds-icon-2xs': 'var(--ds-icon-2xs)',
        'ds-icon-xs': 'var(--ds-icon-xs)',
        'ds-icon-sm': 'var(--ds-icon-sm)',
        'ds-icon-md': 'var(--ds-icon-md)',
        'ds-icon-lg': 'var(--ds-icon-lg)',
        'ds-icon-xl': 'var(--ds-icon-xl)',
        'ds-icon-2xl': 'var(--ds-icon-2xl)',
      },
    },
  },
  plugins: [],
}
