/**
 * Design System Token Test Page
 *
 * Purpose: Verify that design system token utilities are properly generated by Tailwind
 *
 * Test Cases:
 * 1. Spacing utilities (p-ds-*, px-ds-*, py-ds-*, m-ds-*, etc.)
 * 2. Gap utilities (gap-ds-*)
 * 3. Icon sizing utilities (h-ds-icon-*, w-ds-icon-*)
 * 4. Width utilities (max-w-ds-dialog-*)
 *
 * How to use:
 * 1. Start dev server: npm run dev
 * 2. Navigate to: http://localhost:3000/token-test
 * 3. Inspect elements to verify CSS variables are applied
 * 4. Compare with Expected Results below
 */

export default function TokenTestPage() {
  return (
    <div className="min-h-screen bg-background p-8">
      <div className="max-w-4xl mx-auto space-y-8">
        <header>
          <h1 className="text-3xl font-bold mb-4">Design System Token Test</h1>
          <p className="text-muted-foreground">
            Inspect each element below to verify tokens are working.
            Expected: CSS should show <code>var(--ds-spacing-*)</code> values.
          </p>
        </header>

        {/* Test 1: Padding Utilities */}
        <section className="border rounded-lg p-4">
          <h2 className="text-xl font-semibold mb-4">Test 1: Padding Utilities</h2>
          <div className="space-y-2">
            <div className="bg-blue-100 p-ds-sm">
              <code>p-ds-sm</code> - Expected: padding: var(--ds-spacing-sm) = 0.5rem (8px)
            </div>
            <div className="bg-blue-100 p-ds-md">
              <code>p-ds-md</code> - Expected: padding: var(--ds-spacing-md) = 0.75rem (12px)
            </div>
            <div className="bg-blue-100 p-ds-lg">
              <code>p-ds-lg</code> - Expected: padding: var(--ds-spacing-lg) = 1rem (16px)
            </div>
            <div className="bg-blue-100 px-ds-md py-ds-sm">
              <code>px-ds-md py-ds-sm</code> - Expected: px=12px, py=8px
            </div>
          </div>
        </section>

        {/* Test 2: Gap Utilities */}
        <section className="border rounded-lg p-4">
          <h2 className="text-xl font-semibold mb-4">Test 2: Gap Utilities</h2>
          <div className="flex gap-ds-sm bg-green-100 p-2">
            <div className="bg-white p-2">Item 1</div>
            <div className="bg-white p-2">Item 2</div>
            <div className="bg-white p-2">Item 3</div>
          </div>
          <p className="text-sm text-muted-foreground mt-2">
            <code>gap-ds-sm</code> - Expected: gap: var(--ds-gap-sm) = 0.5rem (8px)
          </p>
        </section>

        {/* Test 3: Icon Sizing */}
        <section className="border rounded-lg p-4">
          <h2 className="text-xl font-semibold mb-4">Test 3: Icon Sizing</h2>
          <div className="flex items-center gap-4">
            <div className="h-ds-icon-sm w-ds-icon-sm bg-red-500"></div>
            <code>h-ds-icon-sm w-ds-icon-sm</code> (16px × 16px)

            <div className="h-ds-icon-md w-ds-icon-md bg-red-500"></div>
            <code>h-ds-icon-md w-ds-icon-md</code> (20px × 20px)

            <div className="h-ds-icon-lg w-ds-icon-lg bg-red-500"></div>
            <code>h-ds-icon-lg w-ds-icon-lg</code> (24px × 24px)
          </div>
        </section>

        {/* Test 4: Margin & Spacing Combinations */}
        <section className="border rounded-lg p-4">
          <h2 className="text-xl font-semibold mb-4">Test 4: Margin & Space Utilities</h2>
          <div className="space-y-ds-sm">
            <div className="bg-purple-100 p-2">Item 1</div>
            <div className="bg-purple-100 p-2">Item 2</div>
            <div className="bg-purple-100 p-2">Item 3</div>
          </div>
          <p className="text-sm text-muted-foreground mt-2">
            <code>space-y-ds-sm</code> - Expected: margin-top: 0.5rem on items 2 & 3
          </p>
        </section>

        {/* Test 5: Dialog Width Tokens */}
        <section className="border rounded-lg p-4">
          <h2 className="text-xl font-semibold mb-4">Test 5: Dialog Width Tokens</h2>
          <div className="max-w-ds-dialog-md mx-auto bg-yellow-100 p-4">
            <code>max-w-ds-dialog-md</code> - Expected: max-width: var(--ds-width-dialog-md) = 28rem
          </div>
        </section>

        {/* Diagnostic Info */}
        <section className="border rounded-lg p-4 bg-muted">
          <h2 className="text-xl font-semibold mb-4">Diagnostic Checklist</h2>
          <div className="space-y-2 text-sm">
            <div className="flex items-start gap-2">
              <input type="checkbox" id="check1" />
              <label htmlFor="check1">All colored boxes are visible with proper spacing</label>
            </div>
            <div className="flex items-start gap-2">
              <input type="checkbox" id="check2" />
              <label htmlFor="check2">Inspecting elements shows <code>var(--ds-*)</code> CSS variables</label>
            </div>
            <div className="flex items-start gap-2">
              <input type="checkbox" id="check3" />
              <label htmlFor="check3">CSS variables resolve to actual pixel values</label>
            </div>
            <div className="flex items-start gap-2">
              <input type="checkbox" id="check4" />
              <label htmlFor="check4">No console errors about missing classes</label>
            </div>
          </div>

          <div className="mt-4 p-3 bg-white border rounded">
            <p className="font-semibold">If all checks pass:</p>
            <p>✅ Token utilities are working correctly - safe to proceed with component tokenization</p>

            <p className="font-semibold mt-3">If any checks fail:</p>
            <p>❌ Need to debug Tailwind configuration before proceeding</p>
          </div>
        </section>
      </div>
    </div>
  );
}
