import { Note, Insight } from "./types";

export const sampleNotes: Note[] = [
  {
    id: "1",
    title: "Counter-Attack Training Ideas",
    content: "Observed that we're losing possession too easily in midfield transitions. Need to work on:\n\n- Quick switching play\n- Better body positioning when receiving under pressure\n- Trigger moments for press resistance\n\nConsider using small-sided games with overloads to simulate pressure situations.",
    tags: ["counter-attack", "transitions", "training-ideas", "pressing"],
    category: "Training Session",
    priority: "high",
    createdAt: new Date(2024, 0, 15),
    updatedAt: new Date(2024, 0, 15),
    starred: true,
  },
  {
    id: "2", 
    title: "Player Development - Marcus",
    content: "Marcus showing great improvement in 1v1 situations but still needs work on:\n\n- Decision making in final third\n- Left foot finishing\n- Defensive work rate when we lose possession\n\nSet up individual sessions focusing on shooting with weaker foot.",
    tags: ["player-development", "marcus", "finishing", "1v1"],
    category: "Player Development",
    priority: "medium",
    voiceNote: "voice-note-url",
    createdAt: new Date(2024, 0, 14),
    updatedAt: new Date(2024, 0, 14),
  },
  {
    id: "3",
    title: "Opposition Analysis - City United",
    content: "Scouted City United vs Rovers last week. Key observations:\n\n- Play out from back with short passes\n- Vulnerable to high press on their left side\n- Striker drops deep, creating space behind\n- Wing-backs get forward but leave space in behind\n\nStrategy: Press their left center-back early, exploit space behind wing-backs with through balls.",
    tags: ["opposition-analysis", "city-united", "press", "wing-backs"],
    category: "Match Preparation", 
    priority: "high",
    images: ["formation-diagram-1", "heatmap-analysis"],
    createdAt: new Date(2024, 0, 13),
    updatedAt: new Date(2024, 0, 13),
  },
  {
    id: "4",
    title: "Set Piece Variations",
    content: "New corner routine ideas from watching Premier League analysis:\n\n1. Short corner with overlap run\n2. Far post delivery with late arriving midfielder\n3. Dummy run at near post to create space\n\nPractice these in Thursday session before weekend match.",
    tags: ["set-pieces", "corners", "match-prep", "variations"],
    category: "Tactical Analysis",
    priority: "medium",
    createdAt: new Date(2024, 0, 12),
    updatedAt: new Date(2024, 0, 12),
    starred: true,
  },
  {
    id: "5",
    title: "Team Meeting Notes",
    content: "Discussed with players about maintaining intensity for full 90 minutes. Key points raised:\n\n- Better communication in final 20 minutes\n- Stick to game plan when leading\n- Support teammates making mistakes\n\nPositive response from squad, good buy-in on new pressing triggers.",
    tags: ["team-meeting", "communication", "intensity", "leadership"],
    category: "Team Management",
    priority: "low",
    createdAt: new Date(2024, 0, 11),
    updatedAt: new Date(2024, 0, 11),
  },
];

export const sampleInsights: Insight[] = [
  {
    id: "1",
    type: "trend",
    title: "Increased Focus on Tactical Training",
    description: "Your notes show 60% more tactical content this month compared to last month, with particular emphasis on pressing and transitions.",
    category: "Training Patterns",
    priority: "medium",
    createdAt: new Date(2024, 0, 15),
  },
  {
    id: "2",
    type: "suggestion", 
    title: "Player Development Opportunities",
    description: "Based on your recent player notes, consider creating individual development plans for 3 key players who appear frequently in your observations.",
    actionItems: [
      "Create individual training program for Marcus focusing on weak foot finishing",
      "Set up 1v1 sessions for defensive positioning work",
      "Schedule additional tactical meetings with midfield players"
    ],
    category: "Player Development",
    priority: "high",
    createdAt: new Date(2024, 0, 14),
  },
  {
    id: "3",
    type: "alert",
    title: "Opposition Analysis Gap",
    description: "You have upcoming matches against teams you haven't analyzed recently. Consider scheduling scouting sessions.",
    actionItems: [
      "Scout Riverside FC's last 3 matches",
      "Review defensive transitions patterns of next 2 opponents",
      "Update opposition profiles in match preparation"
    ],
    category: "Match Preparation", 
    priority: "high",
    createdAt: new Date(2024, 0, 13),
  },
  {
    id: "4",
    type: "achievement",
    title: "Consistent Note-Taking Streak",
    description: "Congratulations! You've maintained daily coaching observations for 2 weeks straight. This consistency will improve your tactical analysis.",
    category: "Coaching Development",
    priority: "low",
    createdAt: new Date(2024, 0, 12),
  },
  {
    id: "5",
    type: "suggestion",
    title: "Training Session Optimization",
    description: "Your notes suggest repetitive themes. Consider varying training focus to address different aspects of your game model.",
    actionItems: [
      "Plan possession-based session for Thursday",
      "Add crossing and finishing drills to weekly rotation", 
      "Include more small-sided games for decision making"
    ],
    category: "Session Planning",
    priority: "medium", 
    createdAt: new Date(2024, 0, 11),
  },
];